/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import React, { useEffect, useRef, useMemo } from "react";
import * as THREE from "three";
import { SkeletonUtils } from "three-stdlib";

export function Avatar(props) {
  const { animation = "Standing" } = props;
  const group = useRef();
  
  // Load models and animations from public directory
  const { scene } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  const { animations: standingAnimation } = useFBX(
    "/animations/StandingIdle.fbx"
  );

  // FIX: Give the base skeleton a default +90 deg X rotation AND correct height BEFORE animations bind.
  // This perfectly cancels out the -90 deg rotation on the parent group, ensuring the
  // "base pose" is standing up. By also grabbing the starting position from the animation,
  // we prevent the character from sinking into the floor during crossfades.
  if (!nodes.Hips.userData.rotationFixed) {
    nodes.Hips.quaternion.setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2);
    
    // Grab the starting position of the Hips from the Standing animation
    const posTrack = standingAnimation[0].tracks.find(t => t.name.includes("Hips.position"));
    if (posTrack && posTrack.values.length >= 3) {
      nodes.Hips.position.set(posTrack.values[0], posTrack.values[1], posTrack.values[2]);
    }
    
    nodes.Hips.userData.rotationFixed = true;
  }
  const { animations: wavingAnimation } = useFBX(
    "/animations/Waving.fbx"
  );
  const { animations: typing2Animation } = useFBX(
    "/animations/Typing2.fbx"
  );

  standingAnimation[0].name = "Standing";
  wavingAnimation[0].name = "Waving";
  typing2Animation[0].name = "Typing2";

  const { actions } = useAnimations(
    [
      standingAnimation[0],
      wavingAnimation[0],
      typing2Animation[0],
    ],
    group
  );



  const previousAction = useRef(null);

  useEffect(() => {
    const action = actions?.[animation];
    if (action) {
        action.reset().play();
        
        // Smoothly crossfade from the previous animation
        if (previousAction.current && previousAction.current !== action) {
            action.crossFadeFrom(previousAction.current, 0.5, true);
        }
        
        previousAction.current = action;
    }
  }, [animation, actions]);

  // Make the upper body follow the cursor (Disabled per request)
  /*
  useFrame((state) => {
    if (group.current) {
      // Find the spine and head bones
      const spine = group.current.getObjectByName("Spine2");
      const head = group.current.getObjectByName("Head");
      
      if (spine && head) {
        // state.pointer x and y range from -1 to 1
        const mouseX = state.pointer.x;
        const mouseY = state.pointer.y;

        // The animation engine has already applied this frame's rotation.
        // We just gently ADD an offset so he looks toward the mouse!
        // We spread it between the spine and head so it looks natural.
        
        // Twist left/right
        spine.rotation.y += mouseX * 0.3;
        head.rotation.y += mouseX * 0.4;
        
        // Bend up/down (added a positive offset so he naturally looks slightly downward)
        spine.rotation.x += 0.05 - (mouseY * 0.1);
        head.rotation.x += 0.1 - (mouseY * 0.095);
      }
    }
  });
  */

  return (
    <group {...props} ref={group} dispose={null}>
      <group rotation-x={-Math.PI / 2}>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Wolf3D_Body}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Wolf3D_Outfit_Bottom}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Wolf3D_Hair.geometry}
          material={materials.Wolf3D_Hair}
          skeleton={nodes.Wolf3D_Hair.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        />
        <skinnedMesh
          frustumCulled={false}
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Head"
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Wolf3D_Skin}
          skeleton={nodes.Wolf3D_Head.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
        />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Teeth"
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Wolf3D_Teeth}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");
